"""empty message

Revision ID: 6f828a02da19
Revises: 19339976cabe
Create Date: 2025-09-21 00:44:08.245113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f828a02da19'
down_revision = '19339976cabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('minutes_to_complete',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('minutes_to_complete',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
